const List<Map<String, dynamic>> expensesCategoriesJson = [
  {"name": "Diğer", "imagePath": "diger.svg", "id": 0},
  {"name": "Çocuklar", "imagePath": "cocuk.svg", "id": 1},
  {"name": "Araba", "imagePath": "araba.svg", "id": 2},
  {"name": "Sigorta", "imagePath": "sigorta.svg", "id": 3},
  {"name": "Sigara", "imagePath": "sigara.svg", "id": 4},
  {"name": "Kişisel Bakım", "imagePath": "kisiselbakim.svg", "id": 5},
  {"name": "Kredi Kartı", "imagePath": "kredikarti.svg", "id": 6},
  {"name": "Gıda", "imagePath": "gida.svg", "id": 7},
  {"name": "Yakıt", "imagePath": "yakit.svg", "id": 8},
  {"name": "Su", "imagePath": "su.svg", "id": 9},
  {"name": "Eğitim", "imagePath": "egitim.svg", "id": 10},
  {"name": "Doğal Gaz", "imagePath": "dogalgaz.svg", "id": 11},
  {"name": "Hediye", "imagePath": "hediye.svg", "id": 12},
  {"name": "Bakkaliye", "imagePath": "bakkaliye.svg", "id": 13},
  {"name": "Sağlık", "imagePath": "saglik.svg", "id": 14},
  {"name": "Kira", "imagePath": "kira.svg", "id": 15},
  {"name": "Yatırım", "imagePath": "yatirim.svg", "id": 16},
  {"name": "Elektrik", "imagePath": "elektrik.svg", "id": 17},
  {"name": "İnternet", "imagePath": "internet.svg", "id": 18},
  {"name": "İlaç", "imagePath": "ilac.svg", "id": 19},
  {"name": "Evcil Hayvan", "imagePath": "evcilhayvan.svg", "id": 20},
  {"name": "Eğlence", "imagePath": "eglence.svg", "id": 21},
  {"name": "Alışveriş", "imagePath": "alisveris.svg", "id": 22},
  {"name": "Telefon", "imagePath": "telefon.svg", "id": 23},
  {"name": "Mobilya", "imagePath": "mobilya.svg", "id": 24},
  {"name": "Televizyon", "imagePath": "televizyon.svg", "id": 25},
  {"name": "Fatura", "imagePath": "fatura.svg", "id": 26},
  {"name": "Tamir ve Bakım", "imagePath": "bakim.svg", "id": 27},
  {"name": "Kırtasiye", "imagePath": "kirtasiye.svg", "id": 28},
  {"name": "İçecekler", "imagePath": "icecekler.svg", "id": 29},
  {"name": "Ulaşım", "imagePath": "ulasim.svg", "id": 30},
  {"name": "Spor", "imagePath": "spor.svg", "id": 31},
  {"name": "Tasarruf", "imagePath": "tasarruf.svg", "id": 32},
];
